server:
  port: 8080

spring:
  application:
    name: wallet-app
  datasource:
    url: jdbc:h2:mem:wallet
    username: sa
    password: password
  liquibase:
    change-log: /db/changelog-master.xml

users:
  filepath: /users.csv